version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongocli:
    image: mongo-express  
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_AUTH_DATABASE: "main"
      ME_CONFIG_MONGODB_AUTH_USERNAME: "root"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "example"
    ports:
      - 8081:8081
  
    